[package]
name = "zokrates"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version="1", features= ["full"]}
prost = "0.12"
tonic-reflection = "0.11"	# for dev
tonic = "0.11.0"
hex = "0.4.3"
flate2 = "1.0.30"

[build-dependencies]
tonic-build = "0.11"
